name: run-3d
options:
  bundleIdPrefix: com.run3d
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  run-3d:
    type: application
    platform: macOS
    sources:
      - path: run-3d
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.run3d.run3d
        PRODUCT_NAME: run-3d
        INFOPLIST_FILE: run-3d/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
    info:
      path: run-3d/Info.plist
      properties:
        CFBundleName: run-3d
        CFBundleDisplayName: 极限跑酷
        CFBundleIdentifier: com.run3d.run3d
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: run-3d
        LSMinimumSystemVersion: "13.0"
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        NSSupportsAutomaticTermination: true
        NSSupportsSuddenTermination: false

schemes:
  run-3d:
    build:
      targets:
        run-3d: all
    run:
      config: Debug
